# stage1 - build node app first 
FROM node:19-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY . .
# Install dependencies (npm ci makes sure the exact versions in the lockfile gets installed)
RUN npm install nx --location=global 
RUN npm --prefix back-end install --omit=dev

# stage 2 - build the final image and copy the node_modules and app files only
FROM node:19-alpine
WORKDIR /app
COPY --from=build /app/back-end/node_modules node_modules
COPY back-end/ .
EXPOSE 5000
CMD ["node", "server.js"]