# stage1 - build react app first 
FROM node:18-alpine as build-frontend

ARG API_KEY
ENV REACT_APP_GOOGLE_MAPS_API_KEY=$API_KEY

WORKDIR /app
COPY . .
# Install dependencies (npm ci makes sure the exact versions in the lockfile gets installed)
RUN npm install nx --location=global 
RUN npm install
# Build the app
RUN nx build uct-locator-front-end

# stage 2 - build the final image and copy the react build files
FROM nginx:1.23.3-alpine
COPY --from=build-frontend /app/front-end/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]