name: Deployment
# on: [workflow_dispatch]

on:
  pull_request:
      branches:
        - iac-setup

# inputs:
#     version:
#       description: Bump Version
#       default: v0.0.3
#       required: true
# 
# echo '${{ github.event.inputs.version }}'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v3
  
  diff-dev:
    runs-on: 'ubuntu-latest'
    needs: build-and-publish
    steps:
      # Do diff here
      - name: Checkout
        uses: actions/checkout@v3

  deploy-dev:
    runs-on: 'ubuntu-latest'
    environment: 'development'
    needs: diff-dev
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      # Do diff here
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::680389281752:role/CentralIacStack-developmentGithubActionsRole706010-9AE2R69Z8YJG
          aws-region: us-east-1
  
  diff-prod:
    runs-on: 'ubuntu-latest'
    needs: [build-and-publish, deploy-dev]
    steps:
      # Do diff here
      - name: Checkout
        uses: actions/checkout@v3

  deploy-prod:
    runs-on: 'ubuntu-latest'
    environment: 'production'
    needs: diff-prod
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      # Do diff here
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::680389281752:role/CentralIacStack-productionGithubActionsRole9D7F200-9JAEYPJIOEL2
          aws-region: us-east-1